### ISSUE TITLE
Web directory model is too simple

### ISSUE THREAD

**Issue by ilyaglow** [lair-framework/go-lair#1]
Hi,

I started to code a drone for [wfuzz](https://github.com/xmendez/wfuzz) json output and noticed that web directory model in Lair doesn't provide a lot. 

It would be really nice to have useful fields such as at least request method name and response body size.

I might send a PR for this.

What you think?

**Comment by binary1985** [comment]
Great idea. May want to expand it a bit to support web app testing
methodology even further than that.

**Comment by tomsteele** [comment]
@ilyaglow I am down for this, just open up a PR when you're ready.
